FROM golang:1.22.5 AS builder

WORKDIR /app

COPY . .

RUN go mod download

RUN cd web && go build -o main

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y libc6 ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/wait-for-it.sh .
COPY --from=builder /app/web/main .
COPY --from=builder /app/web/wait-for-services.sh .
COPY --from=builder /app/web/conf_docker.ini ./conf.ini


CMD ["/sh"]