version: "2.8"

services:
  oracle-public-api:
    image: oracle.public-api
    entrypoint: ["./wait-for-services.sh", "./main"]
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - "3020:3020"
    networks:
      - mysqlnetwork
    restart: always

networks:
  mysqlnetwork:
    external: true
